### ISSUE TITLE
NEW local variables in non-procedureblock methods

### ISSUE THREAD

**Issue by timleavitt** [intersystems-ru/Log#1]
In App.Log, the WriteJSONFromObject and LoadContext methods are defined as not procedureblock. The approach in LoadContext, killing all the local variables at the end, is incorrect. The right way to avoid leak of variables (which should be used in both cases) is to NEW all the local variables at the beginning of the method.

It might also be worth giving the local variable names in LoadContext more obscure names to avoid conflicts with argument names (since these actually *should* "leak").

**Comment by eduard93** [comment]
Thank you, @timleavitt. Fixed.

**Comment by timleavitt** [comment]
Looks good to me - thanks @eduard93 !
